### ISSUE TITLE
Unexpected `Error: Non-relative paths are not allowed when 'baseUrl' is not set. Did you forget a leading './'?`

### ISSUE THREAD

**Issue by JounQin** [privatenumber/get-tsconfig#17]
https://github.com/vitejs/vite/runs/7047103190?check_suite_focus=true#step:10:93

reproduction: https://github.com/JounQin/vite/tree/chore/tsx_esno

run `pnpm i && pnpm build`

Maybe related to #16

**Comment by privatenumber** [comment]
Please provide a minimal reproduction and explain why this is a bug.

`pnpm run build` runs so many commands I have to investigate which one is causing it and which tsconfig.json is problematic.

**Comment by JounQin** [comment]
@privatenumber Please help to review #18
