### ISSUE TITLE
Resolve error: File not found when using yarn PnP linker

### ISSUE THREAD

**Issue by meriouma** [privatenumber/get-tsconfig#26]
We have this extends in our tsconfig.json
```
"extends": "@equisoft/typescript-config/tsconfig.standards.json"
```

I took a look at #21 and it seems the `resolveExtends` expects the extend to be in `node_modules`.

Discovered this issue while trying to update to eslint-import-resolver-typescript@v3 which uses this library.

**Comment by privatenumber** [comment]
Can you open a PR with a failing test case that reflects the problem you're describing?

**Comment by meriouma** [comment]
I'm not sure this can be reproduced in a test case, as it's dependent on Node's module resolution when using yarn's PnP linker. I can submit a PR that fixes the issue, but I don't know how to test it.

**Comment by meriouma** [comment]
I created a branch on one of our public repository : https://github.com/kronostechnologies/tax-ca/tree/get-tsconfig-issue
You can see the error when running eslint with `yarn eslint` after running `yarn install`

**Comment by privatenumber** [comment]
Please provide a **minimal** reproduction if you want my help.

A minimal reproduction would have `get-tsconfig` as a direct dependency and no `eslint`.

Sorry but I don't use yarn pnp and I'm happy to help but I don't have time to debug any large codebase.

**Comment by privatenumber** [comment]
Closed via https://github.com/privatenumber/get-tsconfig/pull/28
