### ISSUE TITLE
Support jsconfig.json

### ISSUE THREAD

**Issue by rbong** [privatenumber/get-tsconfig#34]
It would be nice to support [jsconfig.json](https://code.visualstudio.com/docs/languages/jsconfig).

They're distinct files, in that they are configuration files for two different languages, so you can't necessarily use `tsconfig.json` in its place. Next.js for instance doesn't allow you to compile a project as a Javascript project using `tsconfig.json`.

However they are made by the same team and serve some of the same purposes, so it would be great to have an option to use the same package to get it, rather than have an entirely new package just to add support for one variant.

This issue comes from https://github.com/import-js/eslint-import-resolver-typescript/issues/73

**Comment by rbong** [comment]
I didn't have a very good example - that doesn't work either.

```js
getTsconfig("./projectWithJsconfig/jsconfig.json")
// null
```

**Comment by JounQin** [comment]
You have to provide a reproduction then.

**Comment by rbong** [comment]
If you prefer a repo: https://github.com/rbong/get-tsconfig-jsconfig-bug-example

**Comment by JounQin** [comment]
Sorry, it should be

```js
console.log(require('get-tsconfig').getTsconfig('.', 'jsconfig.json'))
```

**Comment by rbong** [comment]
You are right, it works in that case. Bug is not on get-tsconfig's side
