### ISSUE TITLE
Doesn't support extends: absolute path

### ISSUE THREAD

**Issue by andykog** [privatenumber/get-tsconfig#39]
This kind of tsconfig.json is not supported:
```json
{"extends": "/Users/ak/proj/foo/node_modules/bar/tsconfig.json"}
```
I could create a PR fixing this but looks like [fs-fixture](https://github.com/privatenumber/fs-fixture) doesn't support absolute paths either (unless I'm missing something)

**Comment by privatenumber** [comment]
You'll need to provide a reproduction.

Feel free to open a PR with a failing test.

**Comment by andykog** [comment]
Done @privatenumber

**Comment by privatenumber** [comment]
Fixed & released in https://github.com/privatenumber/get-tsconfig/releases/tag/v4.3.0
