### ISSUE TITLE
Support `"exports"` in package.json

### ISSUE THREAD

**Issue by mark-dr** [privatenumber/get-tsconfig#47]
In [`resolve-extends-path.ts`](https://github.com/privatenumber/get-tsconfig/blob/002798158c8467487d2b47b7d59632a01f09e8bf/src/parse-tsconfig/resolve-extends-path.ts#L109), there's some custom logic that uses `findUp` to approximate the Node module resolution algorithm. It works for the classic style of module resolution, but doesn't implement the newer `"exports"` field in `package.json`. This causes failures in my use case (I have a monorepo with a package containing config files, and I want to do things like: `"extends": "@my-worktree/configs/typescript/react"`, with `@my-worktree/configs`'s package.json's `"exports"` mapping that to a `tsconfig-react.json` file in that package)

Would it be an option to use `require.resolve` as a primary or fallback mechanism in that extends resolution code, to offload the work to Node itself? (I'm guessing that's what TypeScript itself does - I've tested and confirmed that it respects the `"exports"` config when resolving `extends`-es)

**Comment by privatenumber** [comment]
I think it should be fairly easy to support with [resolve-pkg-maps](https://github.com/privatenumber/resolve-pkg-maps).

Would you be open to tackling it?
