### ISSUE TITLE
baseUrl should not be required

### ISSUE THREAD

**Issue by alex-kinokon** [privatenumber/get-tsconfig#52]
Error:

```
Resolve error: Non-relative paths are not allowed when 'baseUrl' is not set. Did you forget a leading './'?
```

It’s perfectly valid to use `paths` in TypeScript without setting `baseUrl`, see https://github.com/microsoft/TypeScript/pull/40101.

**Comment by privatenumber** [comment]
Not in my experience. Can you demonstrate?

**Comment by alex-kinokon** [comment]
[Demo](https://stackblitz.com/edit/stackblitz-webcontainer-api-starter-jaknje?file=src%2Findex.ts)

**Comment by privatenumber** [comment]
Thanks, would you be open to contributing a PR?

**Comment by privatenumber** [comment]
In your demo, can you show where `get-tsconfig` is throwing the error where `tsc` is not?
