### ISSUE TITLE
Maximum call stack size exceeded when using extends from node_modules

### ISSUE THREAD

**Issue by kanoshin** [privatenumber/get-tsconfig#55]
Reproduction repository: https://github.com/kanoshin/get-tsconfig-repro

When `tsconfig.json` extends from npm package installed as a dependency, `get-tsconfig` fails with a `Maximum call stack size exceeded` exception:
```
{
    "extends": "@servicetitan/startup/tsconfig/base",
    "compilerOptions": {
        "module": "commonjs",
        "outDir": "dist",
        "rootDir": "src"
    },
    "include": ["src/**/*"],
    "exclude": ["src/**/__tests__/**/*"]
}

```

TypeScript allows you to extend config from an npm package, which is expected to work properly.

**Comment by privatenumber** [comment]
Can you verify this is fixed in https://github.com/privatenumber/get-tsconfig/releases/tag/v4.7.0
