### ISSUE TITLE
Does not handle tsconfig without `baseUrl`

### ISSUE THREAD

**Issue by andreww2012** [privatenumber/get-tsconfig#58]
### Problem

A "continuation" of #50 😅

Nuxt 3.7.x changed the format of generated `tsconfig` again, which now less uses absolute paths but most importantly for some reason does not include `baseUrl` field. This causes `get-tsconfig` to resolve `baseUrl` to `undefined` and again [`eslint-import-resolver-typescript`](https://www.npmjs.com/package/eslint-import-resolver-typescript) not to work properly.

### Expected behavior

Resolved `baseUrl` must not be set to `undefined`, I guess.

### Minimal reproduction URL

https://github.com/andreww2012/eslint-plugin-import-with-nuxt-3.6-false-reports

### Version

v4.7.0

### Node.js version

v16.20.2

### Package manager

pnpm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Like your previous issue, your reproduction is not minimal at all.

Can you update it to demonstrate that `tsc` emits an error? Happy to re-open once it's minimal.

**Comment by andreww2012** [comment]
I'm sorry, but could you help me understand what needs to be changed to make it more minimal?

- All that is required from Nuxt is to generate `.nuxt/tsconfig.json` file. That's it. Why I'm not including the pre-generated `tsconfig`? Because it may contain absolute paths.
- My repro script is `get-tsconfig.js` which invokes this library's exported functions directly.
- My 2nd another repro script lints the repo with ESLint, but this one exists just to test whether false errors are reported with the current dependencies.

Full reproduction instructions can be found in the README of that repository.

**Comment by andreww2012** [comment]
Actually, if resolving `baseUrl` to `undefined` if it's missing from the input tsconfig is an expected behaviour, I should probably redirect this issue directly to [eslint-import-resolver-typescript](https://www.npmjs.com/package/eslint-import-resolver-typescript). They probably don't expect `baseUrl` to not present since it was made optional since TypeScript 4.1 provided that `paths` are used (https://www.typescriptlang.org/tsconfig#baseUrl)

**Comment by andreww2012** [comment]
I'm suspecting this section of code may cause the problem.

In `resolveExtends`, `baseUrl` is set to `./` if it's empty:

https://github.com/privatenumber/get-tsconfig/blob/c834d2322f560754b2a857fe2a94ad619908991c/src/parse-tsconfig/index.ts#L36-L48

In `parseTsConfig` this is not the case:

https://github.com/privatenumber/get-tsconfig/blob/c834d2322f560754b2a857fe2a94ad619908991c/src/parse-tsconfig/index.ts#L146-L163

**Comment by privatenumber** [comment]
What makes a reproduction _minimal_ is that there is nothing extra. Specifically, if I can delete a file or code and still reproduce the bug, the repro is not minimal.

In contrast, your repro has 10 dependencies, 7 script commands, and over 10 files just in the root.

I work on this project for free but I'm not providing free debugging support, so it's up to the users to _prove_ that there's a bug without creating more work. If you need closer assistance, you can consider [sponsoring me for Priority Support](https://github.com/sponsors/privatenumber).

**Comment by privatenumber** [comment]
Thanks. I added a failing test case in https://github.com/privatenumber/get-tsconfig/issues/58 (In the future, it may be a lot easier to open a PR with a failing test).

I don't have time to work on a fix right now but feel free to investigate why this is happening.
