### ISSUE TITLE
Error: Circularity detected while resolving configuration

### ISSUE THREAD

**Issue by 13OnTheCode** [privatenumber/get-tsconfig#67]
### Problem

If the `extends` configuration in `tsconfig.json` is an array, and each item in it further `extends` another configuration, it will cause `getTsconfig` to run and fail, with the following error message:

```
Error: Circularity detected while resolving configuration: /home/projects/vitest-dev-vitest-wulihl/tsconfigs/base.json
    at _0x15be0c._evaluate (https://vitestdevvitestwulihl-g131.w-corp-staticblitz.com/blitz.c9a8a620.js:352:379484)
    at async ModuleJob.run (https://vitestdevvitestwulihl-g131.w-corp-staticblitz.com/blitz.c9a8a620.js:181:2372)
```

### Expected behavior

-

### Minimal reproduction URL

https://stackblitz.com/edit/vitest-dev-vitest-wulihl?file=repro.mjs

### Version

v4.7.2

### Node.js version

v18.18.0

### Package manager

npm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Thanks for the report!

Happy to accept a PR if anyone wants to work on this.

**Comment by hi-ogawa** [comment]
@13OnTheCode Thanks! I was going to move the issue here, but I just noticed you've already done.

FYI, this is the downstream issue in Vitest typecheck mode:
- https://github.com/vitest-dev/vitest/issues/5326

**Comment by privatenumber** [comment]
Thanks for reporting further impact. Will try to look into this by the end of the week.
