### ISSUE TITLE
replaceAll syntax issue with webpack's bundler in files-matcher.ts

### ISSUE THREAD

**Issue by Michael2013518** [privatenumber/get-tsconfig#69]
### Problem

In Vue2.X project, esbuild-loader which relies on get-tsconfig is used for packaging, There throw an exception in the cjs file "UnhandledPromiseRejectionWarning: TypeError: E.placeall is not a function ", this seems to be an unnecessary syntax upgrade in 4.7.3, please check it out.

### Expected behavior

Use the replace syntax instead of replaceAll

### Minimal reproduction URL

https://stackblitz.com/edit/can't-be-supported-in-vue2-with-webpack

### Version

v4.7.3

### Node.js version

v14.18.0

### Package manager

npm

### Operating system

Windows

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
You need to uprade Node.

Node v14 reached EOL in 2020: https://endoflife.date/nodejs
