### ISSUE TITLE
`paths` resolution is broken in v4.7.5

### ISSUE THREAD

**Issue by mrazauskas** [privatenumber/get-tsconfig#78]
### Problem

As mentioned in https://github.com/privatenumber/get-tsconfig/pull/77#issuecomment-2106651097, the latest release of `get-tsconfig` (v4.7.5) breaks `paths` resolution.

As I mentioned, TSConfig has the following map specified:

```json
"paths": {
  "#*": ["./*/index.ts"]
},
```

To reproduce the problem, I use `createPathsMatcher()` example from the [readme](https://github.com/privatenumber/get-tsconfig?tab=readme-ov-file#createfilematchertsconfig-tsconfigresult-casesensitivepaths-boolean). TSConfig file is loaded from `<path-to-project>/source/tsconfig.json` and passed to `createPathsMatcher()`.

- before v4.7.5 `pathsMatcher('#sample')` resolves to: `<path-to-project>/source/sample/index.ts`.
- since v4.7.5`pathsMatcher('#sample')` resolves to: `<path-to-project>/source/source/sample/index.ts`

### Expected behavior

It should not break.

### Minimal reproduction URL

https://github.com/privatenumber/get-tsconfig?tab=readme-ov-file#createfilematchertsconfig-tsconfigresult-casesensitivepaths-boolean

### Version

v4.7.5

### Node.js version

lts

### Package manager

npm

### Operating system

macOS

### Contributions

- [ ] I plan to open a pull request for this issue
- [ ] I plan to make a financial contribution to this project

**Comment by privatenumber** [comment]
Thanks for the issue but the bug needs to be proven with a minimal reproduction to be confirmed.

Let me know once it's been updated and I'll reopen.

**Comment by mrazauskas** [comment]
You are simply ignorant and arrogant. I can't provide reproduction for that.

**Comment by privatenumber** [comment]
You're one warning away from getting banned. Please be respectful.

This is project runs on community contributions and you're benefitting from it for free. Take a look at the other issues; everyone else is doing the due diligence of providing a minimal reproduction to prove the bug exists. If you expecting others to do your work for free, please look elsewhere.

**Comment by mrazauskas** [comment]
> please look elsewhere.

Sure. This was the last project I was using ESLint. Thanks for extra motivation to migrate away.
