### ISSUE TITLE
paths matcher in version 4.7.5 resolves incorrect paths

### ISSUE THREAD

**Issue by stefanprobst** [privatenumber/get-tsconfig#79]
### Problem

paths matcher in version 4.7.5 resolves incorrect paths

steps to reproduce:
- `git clone https://github.com/stefanprobst/issue-get-tsconfig && cd issue-get-tsconfig && pnpm install`
- `node index.mjs`
- see a paths ending in "e2e/e2e/src/check.ts" being logged (note the duplicated "e2e")

to see the behavior in previous version 4.7.3, check out branch "previous-version":
- `git checkout previous-version && pnpm install`
- `node index.mjs`
- see a path ending in "e2e/src/check.ts" being logged

### Expected behavior

paths should resolve correctly (like in v4.7.3)

### Minimal reproduction URL

https://github.com/stefanprobst/issue-get-tsconfig

### Version

4.7.5

### Node.js version

20.15.0

### Package manager

pnpm

### Operating system

Linux

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by jordanhboxer** [comment]
also experiencing this with pnpm and tsx
