### ISSUE TITLE
Add support for TS 5.5 `${configDir}` template variable

### ISSUE THREAD

**Issue by zanminkian** [privatenumber/get-tsconfig#81]
### Feature request

TS 5.5 support `${configDir}` template variable. See [here](https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#the-configdir-template-variable-for-configuration-files).

```ts
import { parseTsconfig } from "get-tsconfig";
const tsconfig = parseTsconfig('/path/to/tsconfig.json');
console.log(tsconfig.compileOptions.outDir) // if there is `${configDir}` template variable in `outDir`, the output result is incorrect in TS 5.5
```

### Motivations

To support TS 5.5 `${configDir}` template variable.

### Bugs are expected to be fixed by those affected by it

- [ ] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [ ] I'm willing to offer financial support

**Comment by SukkaW** [comment]
@privatenumber I'd like to create a PR for `${configDir}` support, but I can't get existing test cases to pass after upgrading to TS 5.5 (it seems that there is a behavior change with `--showConfig`). You might wanna take a look at that first.

**Comment by privatenumber** [comment]
Yeah the tests need to be updated when you upgrade `typescript`. I'm not sure when I'll get around to this right now.

**Comment by SukkaW** [comment]
> Yeah the tests need to be updated when you upgrade `typescript`. I'm not sure when I'll get around to this right now.

It seems that the latest `tsc --showConfig` now prints explicit config instead of the original config, hence the extra fields.

**Comment by privatenumber** [comment]
Yep, it's a good thing. get-tsconfig should match this behavior and build-in this logic.

**Comment by SukkaW** [comment]
> Yep, it's a good thing. get-tsconfig should match this behavior and build-in this logic.

Though `tsc --showConfig` now makes the "hidden" default more explicit, I am not sure whether the `get-tsconfig` should do the same, this looks like a breaking change to me.

**Comment by privatenumber** [comment]
Before, it was up to the consumer of get-tsconfig's output to determine what configs are implicitly enabled, but now get-tsconfig does it for you. In terms of behavior, there's no breaking change, but there is a breaking change in terms of API output. I don't mind doing a major release for this.

**Comment by privatenumber** [comment]
RE: https://github.com/dominikg/tsconfck/issues/183

I'm quite occupied with work these days but if it's a priority, I'm happy to support you to get this in.

For now, we can upgrade TypeScript and suppress the extra output. Would you be willing to open a PR?

**Comment by privatenumber** [comment]
Sounds good!

**Comment by SukkaW** [comment]
@privatenumber You might want to re-open this issue. #83 only fixes the test cases are doesn't actually implement the `${configDir}` feature.

**Comment by privatenumber** [comment]
See https://github.com/privatenumber/get-tsconfig/commit/eba85380401a64b6cc3ff8e639fa2391da41c2d2

**Comment by SukkaW** [comment]
> See [eba8538](https://github.com/privatenumber/get-tsconfig/commit/eba85380401a64b6cc3ff8e639fa2391da41c2d2)

Oh I miss that!

**Comment by trikadin** [comment]
doesn't work for me :(
<img width="347" alt="image" src="https://github.com/user-attachments/assets/1c1387ca-1284-45b9-ac96-c608b34458b3">

rootDir defined as follows in a parent tsconfig:
```
"rootDir": "${configDir}/src",
```

**Comment by privatenumber** [comment]
This is a closed issue, please open another one.

Looks like I missed rootDirs and others (declarationDir, typeRoots, baseUrl). Feel free to open a PR
