### ISSUE TITLE
My Node environment doesn't support the replaceAll method for strings, which is causing an error.

### ISSUE THREAD

**Issue by Pateo-fanyang** [privatenumber/get-tsconfig#85]
### Problem

In the following file: src/files-matcher.ts,
there is an escapeForRegexp function. In versions prior to 4.7.2, the conversion was done using replace, but after version 4.7.2, it was replaced with replaceAll. This method is not supported in my Node environment.

I encountered this issue while using the esbuild-loader library, which has a dependency on your library, causing the problem. 

### Expected behavior

Could you revert it back to replace for better compatibility with the Node environment? Thank you!

### Minimal reproduction URL

1

### Version

4.8.1

### Node.js version

v14.20.0

### Package manager

yarn

### Operating system

macOS

### Bugs are expected to be fixed by those affected by it

- [X] I'm interested in working on this issue

### Compensating engineering work financially will speed up resolution

- [X] I'm willing to offer financial support

**Comment by privatenumber** [comment]
Thanks for the issue. We understand that replaceAll is causing compatibility problems with Node.js v14.20.0. However, Node.js v14 reached end-of-life for active support and security updates in April 2023.

We recommend upgrading to Node.js v18 (security support until April 2025) or v20 (security support until April 2026). If upgrading isn’t feasible, you can use version 4.7.1 if it's compatible with Node.js v14.
